[package]
name = "monocle"
version = "0.0.1"
authors = ["Mingwei Zhang <mingwei@bgpkit.com>"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/bgpkit/monocle"
documentation = "https://docs.rs/monocle"
description = """
A library to parse multiple MRT files in parallel and creating timestamp-sorted BGP message stream.
"""
keywords = ["bgp", "bgpkit", "mrt"]

[dependencies]
bgpkit-broker = "0.3"
bgpkit-parser = {git="https://github.com/bgpkit/bgpkit-parser.git", branch="main"}
spmc = "0.3.0"
itertools="0.10.3"
rayon = "1.5.1"
tracing = "0.1"
tracing-subscriber = "0.3.3"