[package]
name = "monocle"
version = "0.0.2"
authors = ["Mingwei Zhang <mingwei@bgpkit.com>"]
edition = "2021"
readme = "README.md"
license = "MIT"
repository = "https://github.com/bgpkit/monocle"
documentation = "https://docs.rs/monocle"
description = """
A commandline application to search, parse, and process BGP information stored in MRT files.
"""
keywords = ["bgp", "bgpkit", "mrt"]

[[bin]]
name = "monocle"
path = "src/monocle.rs"

[dependencies]
bgpkit-broker = "0.4.1"
bgpkit-parser = "0.7.5"
clap = { version = "3.2.8", features = ["derive"] }
itertools="0.10.3"
rayon = "1.5.1"
tracing = "0.1"
tracing-subscriber = "0.3"
ipnetwork = {version="0.18", default-features=false}
serde={version="1.0", features=["derive"]}
serde_json = "1.0"
chrono = "0.4"
anyhow = "1.0"
