[package]
name = "monocle"
version = "0.1.0"
authors = ["Mingwei Zhang <mingwei@bgpkit.com>"]
edition = "2021"
readme = "README.md"
license = "MIT"
repository = "https://github.com/bgpkit/monocle"
documentation = "https://docs.rs/monocle"
description = """
A commandline application to search, parse, and process BGP information in public sources.
"""
keywords = ["bgp", "bgpkit", "mrt"]

[[bin]]
name = "monocle"
path = "src/monocle.rs"

[dependencies]
bgpkit-broker = "0.4.1"
bgpkit-parser = "0.8.1"
clap = { version = "3.2.8", features = ["derive"] }
itertools="0.10.3"
rayon = "1.5.1"
tracing = "0.1"
tracing-subscriber = "0.3"
ipnetwork = {version="0.18", default-features=false}
serde={version="1.0", features=["derive"]}
serde_json = "1.0"
chrono = "0.4"
chrono-humanize = "0.2.1"
anyhow = "1.0"
tabled = "0.8"
config = {version = "0.13.1", features = ["toml"]}
dirs = "4"
rusqlite = { version = "0.28.0", features = ["bundled"] }
reqwest = {version = "0.11", features = ["blocking"]}
regex = "1.6.0"
oneio = "0.3.0"

[features]
scouter = []